### ISSUE TITLE
Macro C_MACRO_COLLECTIONS_GEN() dành cho hashset không hoạt động

### ISSUE THREAD

**Issue by hieutran29** [bangoc/it3240E#1]
Thưa thầy, nếu em sử dụng `C_MACRO_COLLECTIONS_GEN(CMC, HASHSET, (ihs, ihashset, , , int), (STR))` thì code báo lỗi không dùng được iterator. Vậy có cách nào để vẫn sử dụng `C_MACRO_COLLECTIONS_GEN()` mà dùng được iterator không ạ?

**Comment by bangoc** [comment]
> Thưa thầy, nếu em sử dụng `C_MACRO_COLLECTIONS_GEN(CMC, HASHSET, (ihs, ihashset, , , int), (STR))` thì code báo lỗi không dùng được iterator. Vậy có cách nào để vẫn sử dụng `C_MACRO_COLLECTIONS_GEN()` mà dùng được iterator không ạ?

Tham số thứ 4 của C_MACRO_COLLECTIONS_GEN là để tùy chỉnh các mở rộng nhé, em muốn có iterator thì bổ xung thêm thành phần ITER, như vậy sẽ là (ITER, STR).

**Comment by hieutran29** [comment]
Em cảm ơn thầy, code chạy được rồi ạ. Em xin phép đóng issuse này ở đây.
